#!/usr/bin/env python3
"""End-to-end check of done-criterion 3, against a running stack.

The brief's third done criterion is one sentence -- "a request through the
*existing* LiteLLM proxy carrying an Egyptian national ID comes back masked,
and a row lands in pii_events with the correct user_api_key_user_id" -- and it
is the only one that exercises every component at once. This runs it.

    python scripts/verify_end_to_end.py                      # needs the stack up
    python scripts/verify_end_to_end.py --model local-llama  # through the real model

What it asserts, in order:

1. pii-service is healthy and its database is reachable.
2. A virtual key bound to a user id can be minted on the proxy.
3. A request carrying a national ID, a mobile and an IBAN reaches the provider
   with all three replaced by placeholders. The default model is the echo
   fixture, which returns the request verbatim, so this is an assertion about
   what crossed the wire rather than about what a model said about it.
4. Tool-call arguments are masked too -- the gap the brief calls out in
   Presidio's own hook.
5. One audit row per span landed, carrying user_id, team_id, key_alias and
   end_user_id from the virtual key.
6. **No row anywhere in pii_events contains any of the values sent.** This is
   the load-bearing assertion. Everything above can pass on a system that also
   quietly writes the national ID into a column, and that system is a worse
   thing to operate than no audit trail at all.

Fixtures are generated by pii_service.synthetic, never pasted (brief §12).
"""

from __future__ import annotations

import argparse
import json
import random
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "services" / "pii-service" / "src"))

from pii_service.synthetic import (  # noqa: E402
    synthetic_iban,
    synthetic_mobile,
    synthetic_national_id,
    to_arabic_indic,
)

PROXY = "http://127.0.0.1:4000"
USER_ID = "verify-eng-42"
TEAM_ID = "verify-platform"
END_USER = "verify-end-user-7"


class Failure(AssertionError):
    pass


@dataclass
class Fixtures:
    nid: str
    mobile: str
    iban: str

    @property
    def nid_arabic(self) -> str:
        return to_arabic_indic(self.nid)

    def every_value(self) -> list[str]:
        return [self.nid, self.mobile, self.iban, self.nid_arabic, to_arabic_indic(self.mobile)]


def _post(url: str, payload: dict, token: str, timeout: float = 600.0) -> dict:
    request = urllib.request.Request(  # noqa: S310 -- fixed http:// literal above
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310
            return json.load(response)
    except urllib.error.HTTPError as exc:
        raise Failure(f"{url} returned {exc.code}: {exc.read().decode()[:500]}") from exc


def _env(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise Failure(f"{path} not found -- see the README quick start")
    values: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    return values


def _docker(args: list[str], *, check: bool = False) -> subprocess.CompletedProcess[str]:
    """Run a docker command.

    S607 (partial executable path) is accepted deliberately: this is an
    operator tool run from a shell that already has docker on its PATH, and
    hard-coding /usr/bin/docker would break on every host that puts it
    somewhere else.
    """
    return subprocess.run(  # noqa: S603
        ["docker", *args],  # noqa: S607
        capture_output=True,
        text=True,
        timeout=60,
        check=check,
    )


def _psql(env: dict[str, str], sql: str) -> str:
    result = _docker(
        [
            "exec",
            "-e",
            f"PGPASSWORD={env.get('PII_DB_PASSWORD', '')}",
            "pii-db",
            "psql",
            "-U",
            env.get("PII_DB_USER", "pii"),
            "-d",
            env.get("PII_DB_NAME", "pii"),
            "-tAc",
            sql,
        ]
    )
    if result.returncode != 0:
        raise Failure(f"psql failed: {result.stderr.strip()[:400]}")
    return result.stdout.strip()


def _check(label: str, condition: bool, detail: str = "") -> None:
    print(f"  {'PASS' if condition else 'FAIL'}  {label}" + (f"  -- {detail}" if detail else ""))
    if not condition:
        raise Failure(label)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model",
        default="echo",
        help="proxy model to send through. 'echo' asserts on the exact wire text; "
        "'local-llama' proves the path against a real model.",
    )
    parser.add_argument("--seed", type=int, default=20260920)
    arguments = parser.parse_args()

    rng = random.Random(arguments.seed)
    fixtures = Fixtures(
        nid=synthetic_national_id(birth_date=date(1988, 6, 21), governorate_code="12", rng=rng),
        mobile=synthetic_mobile(rng=rng),
        iban=synthetic_iban(rng=rng),
    )

    root_env = _env(REPO_ROOT / ".env")
    proxy_env = _env(REPO_ROOT / "deploy" / "local-litellm" / ".env")
    master_key = proxy_env["LITELLM_MASTER_KEY"]

    print("\n1. pii-service health")
    health = json.loads(
        _docker(
            [
                "exec",
                "pii-service",
                "python",
                "-c",
                "import urllib.request;print(urllib.request.urlopen("
                "'http://127.0.0.1:8090/health',timeout=5).read().decode())",
            ],
            check=True,
        ).stdout
    )
    _check("status ok", health["status"] == "ok", health["status"])
    _check("audit database reachable", health["database_reachable"] is True)

    print("\n2. virtual key bound to a user id")
    key = _post(
        f"{PROXY}/key/generate",
        {"user_id": USER_ID, "key_alias": f"verify-{int(time.time())}", "models": []},
        master_key,
        timeout=60,
    )
    _check("key minted", bool(key.get("key")), f"user_id={key.get('user_id')}")
    _check("carries our user id", key.get("user_id") == USER_ID)

    print(f"\n3. a national ID through the proxy (model={arguments.model})")
    content = (
        f"Please file customer record: national id {fixtures.nid}, "
        f"mobile {fixtures.mobile}, iban {fixtures.iban}. "
        "Reply with one short sentence."
    )
    reply = _post(
        f"{PROXY}/v1/chat/completions",
        {
            "model": arguments.model,
            "user": END_USER,
            "messages": [{"role": "user", "content": content}],
        },
        key["key"],
    )
    answer = reply["choices"][0]["message"]["content"]

    if arguments.model == "echo":
        on_the_wire = json.loads(answer)["messages"][0]["content"]
        print(f"      provider received: {on_the_wire}")
        _check("national ID replaced", "<EG_NATIONAL_ID>" in on_the_wire)
        _check("mobile replaced", "<EG_MOBILE>" in on_the_wire)
        _check("IBAN replaced", "<EG_IBAN>" in on_the_wire)
        for value in (fixtures.nid, fixtures.mobile, fixtures.iban):
            _check("value absent from the wire", value not in on_the_wire)
    else:
        print(f"      model replied: {answer.strip()[:200]}")
        for value in (fixtures.nid, fixtures.mobile, fixtures.iban):
            _check("value absent from the reply", value not in answer)

    print("\n4. tool-call arguments are scanned")
    tool_reply = _post(
        f"{PROXY}/v1/chat/completions",
        {
            "model": "echo",
            "user": END_USER,
            "messages": [
                {"role": "user", "content": "look this up"},
                {
                    "role": "assistant",
                    "tool_calls": [
                        {
                            "id": "c1",
                            "type": "function",
                            "function": {
                                "name": "lookup",
                                "arguments": json.dumps({"nid": fixtures.nid}),
                            },
                        }
                    ],
                },
            ],
        },
        key["key"],
    )
    tool_wire = tool_reply["choices"][0]["message"]["content"]
    _check("tool-call arguments masked", "<EG_NATIONAL_ID>" in tool_wire)
    _check("national ID absent from tool args", fixtures.nid not in tool_wire)

    print("\n5. audit rows, with the identity from the virtual key")
    time.sleep(3)  # the audit write is deliberately off the request path
    # S608: USER_ID is a module constant, not input. psql -tAc takes no bind
    # parameters, and adding a driver to this script to get them would be a
    # heavier dependency than the risk it removes.
    rows = _psql(
        root_env,
        "SELECT entity_type, user_id, end_user_id, field, action, value_fp "  # noqa: S608
        f"FROM pii_events WHERE user_id = '{USER_ID}' ORDER BY id DESC LIMIT 20",
    )
    parsed = [line.split("|") for line in rows.splitlines() if line]
    entities = {row[0] for row in parsed}
    _check("rows landed", bool(parsed), f"{len(parsed)} rows")
    _check("user_api_key_user_id recorded", all(row[1] == USER_ID for row in parsed))
    _check("end user recorded", all(row[2] == END_USER for row in parsed))
    _check("national ID recorded", "EG_NATIONAL_ID" in entities, ", ".join(sorted(entities)))
    _check("tool-call field labelled", any(row[3] == "tool_call.args" for row in parsed))
    _check("every span fingerprinted", all(row[5] for row in parsed))

    print("\n6. no value anywhere in the audit database")
    dump = _psql(root_env, "SELECT * FROM pii_events")
    for value in fixtures.every_value():
        _check(f"...{value[-4:]} absent from every column", value not in dump)

    print("\nEnd-to-end verification passed.\n")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Failure as failure:
        print(f"\nFAILED: {failure}\n", file=sys.stderr)
        raise SystemExit(1) from failure
